import React from "react";
import { AbsoluteFill, Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";

export type EvidenceItem = { label: string; value: string; detail?: string };
export type EvidenceFocus = { scale?: number; x?: number; y?: number };
export type PrimaryEvidenceSpec = {
  kind: "split_documents" | "official_document" | "official_figure" | "official_screen" | "image_sequence" | "source_timeline" | "source_article" | "concept_map" | "boundary" | "comparison" | "recap" | "evidence_chain";
  eyebrow: string; title: string; subtitle?: string; callout?: string; limitation?: string; source_label: string; source_ids: string[]; evidence_asset_ids?: string[]; image_assets?: string[]; items?: EvidenceItem[]; steps?: string[]; left?: string; right?: string; left_detail?: string; right_detail?: string; focus?: EvidenceFocus; font_px?: number;
};

const ink="#F5F0E7", muted="#B9C0C9", blue="#86A9CC", accent="#D95B53", ground="#07101A";
const clamp={extrapolateLeft:"clamp" as const,extrapolateRight:"clamp" as const};
const Panel:React.FC<{children:React.ReactNode;style?:React.CSSProperties}>=({children,style})=><div style={{background:"linear-gradient(145deg,rgba(15,25,38,.96),rgba(7,13,22,.94))",border:"1px solid rgba(245,240,231,.18)",boxShadow:"0 30px 90px rgba(0,0,0,.45)",borderRadius:12,overflow:"hidden",...style}}>{children}</div>;
const SourceBar:React.FC<{spec:PrimaryEvidenceSpec}>=({spec})=><div style={{position:"absolute",left:70,right:70,bottom:146,display:"flex",alignItems:"center",justifyContent:"space-between",gap:24,color:muted,fontFamily:"Arial, Helvetica, sans-serif",fontSize:17,lineHeight:1.15,letterSpacing:".085em",textTransform:"uppercase",fontWeight:760}}><div style={{display:"flex",alignItems:"center",gap:10,minWidth:0}}><span style={{width:8,height:8,borderRadius:99,background:blue,flex:"0 0 auto"}}/><span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{spec.source_label}</span></div><span style={{color:"rgba(245,240,231,.48)",whiteSpace:"nowrap"}}>PRIMARY SOURCE / SOURCE-DERIVED</span></div>;
const Limitation:React.FC<{text?:string}>=({text})=>text?<div style={{position:"absolute",left:70,right:70,bottom:185,borderLeft:`4px solid ${accent}`,background:"rgba(217,91,83,.14)",color:ink,padding:"10px 15px 11px",fontFamily:"Arial, Helvetica, sans-serif",fontSize:20,lineHeight:1.18,fontWeight:720,boxShadow:"0 12px 34px rgba(0,0,0,.25)"}}>{text}</div>:null;
const Header:React.FC<{spec:PrimaryEvidenceSpec}>=({spec})=><div style={{position:"absolute",left:70,right:70,top:48,fontFamily:"Arial, Helvetica, sans-serif",zIndex:5}}><div style={{color:blue,fontSize:18,lineHeight:1.1,letterSpacing:".16em",fontWeight:850}}>{spec.eyebrow}</div><div style={{color:ink,fontSize:Math.max(38,(spec.font_px||31)+8),lineHeight:1.01,letterSpacing:"-.032em",fontWeight:850,marginTop:12,maxWidth:1620}}>{spec.title}</div>{spec.subtitle?<div style={{color:muted,fontSize:25,lineHeight:1.2,fontWeight:560,marginTop:12,maxWidth:1450}}>{spec.subtitle}</div>:null}</div>;

const ImageFrame:React.FC<{src:string;contain?:boolean;focus?:EvidenceFocus;progress:number;style?:React.CSSProperties}>=({src,contain=true,focus,progress,style})=>{const scaleTo=focus?.scale??(contain?1.035:1.07);const scale=interpolate(progress,[0,1],[1,scaleTo],clamp);const x=interpolate(progress,[0,1],[0,focus?.x??0],clamp);const y=interpolate(progress,[0,1],[0,focus?.y??0],clamp);return <div style={{position:"relative",width:"100%",height:"100%",overflow:"hidden",background:contain?"#EEECE6":"#111820",border:"1px solid rgba(245,240,231,.2)",boxShadow:"0 24px 80px rgba(0,0,0,.5)",...style}}><Img src={staticFile(src)} style={{width:"100%",height:"100%",objectFit:contain?"contain":"cover",objectPosition:"center",transform:`translate(${x}%, ${y}%) scale(${scale})`,filter:"contrast(1.025) saturate(.96)"}}/></div>};
const SplitDocuments:React.FC<{spec:PrimaryEvidenceSpec;progress:number}>=({spec,progress})=><div style={{position:"absolute",left:70,right:70,top:190,bottom:spec.limitation?250:190,display:"grid",gridTemplateColumns:"1fr 1fr",gap:26}}>{(spec.image_assets||[]).slice(0,2).map((asset,index)=><ImageFrame key={asset} src={asset} contain focus={{scale:1.02+index*.01,x:index?-.4:.4,y:-1}} progress={progress} style={{borderRadius:10}}/>)}</div>;
const Document:React.FC<{spec:PrimaryEvidenceSpec;progress:number}>=({spec,progress})=><div style={{position:"absolute",left:70,right:70,top:180,bottom:spec.limitation?252:190,display:"grid",gridTemplateColumns:spec.callout?"1.5fr .72fr":"1fr",gap:26}}><ImageFrame src={(spec.image_assets||[])[0]} contain focus={spec.focus} progress={progress} style={{borderRadius:10}}/>{spec.callout?<Panel style={{display:"flex",alignItems:"center",padding:"34px 32px"}}><div><div style={{color:blue,fontSize:17,letterSpacing:".14em",fontWeight:850}}>WHY THIS PAGE MATTERS</div><div style={{color:ink,fontSize:31,lineHeight:1.24,fontWeight:720,marginTop:18}}>{spec.callout}</div></div></Panel>:null}</div>;
const Figure:React.FC<{spec:PrimaryEvidenceSpec;progress:number;screen?:boolean}>=({spec,progress,screen=false})=><div style={{position:"absolute",left:70,right:70,top:178,bottom:spec.limitation?252:190}}><ImageFrame src={(spec.image_assets||[])[0]} contain={!screen} focus={spec.focus} progress={progress} style={{borderRadius:10}}/>{spec.callout?<div style={{position:"absolute",right:26,bottom:26,maxWidth:610,background:"rgba(5,10,17,.9)",border:"1px solid rgba(245,240,231,.22)",borderLeft:`5px solid ${blue}`,color:ink,padding:"18px 21px",fontFamily:"Arial, Helvetica, sans-serif",fontSize:24,lineHeight:1.22,fontWeight:690}}>{spec.callout}</div>:null}</div>;
const ImageSequence:React.FC<{spec:PrimaryEvidenceSpec;progress:number}>=({spec,progress})=><div style={{position:"absolute",left:70,right:70,top:190,bottom:spec.limitation?252:190,display:"grid",gridTemplateColumns:"1fr 1fr",gridTemplateRows:"1fr 1fr",gap:14}}>{(spec.image_assets||[]).slice(0,4).map((asset,index)=><div key={asset} style={{position:"relative",overflow:"hidden",border:"1px solid rgba(245,240,231,.18)",borderRadius:8}}><Img src={staticFile(asset)} style={{width:"100%",height:"100%",objectFit:"cover",transform:`scale(${interpolate(progress,[0,1],[1.015,1.045],clamp)})`,filter:"contrast(1.03) saturate(.92)"}}/><div style={{position:"absolute",left:12,top:10,width:30,height:30,borderRadius:99,display:"grid",placeItems:"center",background:"rgba(7,16,26,.92)",border:`1px solid ${blue}`,color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:16,fontWeight:850}}>{index+1}</div></div>)}</div>;
const Timeline:React.FC<{spec:PrimaryEvidenceSpec;reveal:number}>=({spec,reveal})=><div style={{position:"absolute",left:85,right:85,top:230,bottom:spec.limitation?270:210,display:"grid",gridTemplateColumns:`repeat(${Math.max(1,(spec.items||[]).length)}, 1fr)`,gap:18,alignItems:"stretch"}}>{(spec.items||[]).map((item,index)=>{const local=interpolate(reveal,[index/Math.max(1,(spec.items||[]).length),(index+1)/Math.max(1,(spec.items||[]).length)],[0,1],clamp);return <Panel key={`${item.label}-${item.value}`} style={{opacity:local,transform:`translateY(${(1-local)*20}px)`,padding:"24px 22px",display:"flex",flexDirection:"column"}}><div style={{color:blue,fontFamily:"Arial, Helvetica, sans-serif",fontSize:18,letterSpacing:".12em",fontWeight:850}}>{item.label}</div><div style={{color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:30,lineHeight:1.05,fontWeight:820,marginTop:17}}>{item.value}</div>{item.detail?<div style={{color:muted,fontFamily:"Arial, Helvetica, sans-serif",fontSize:22,lineHeight:1.22,marginTop:15}}>{item.detail}</div>:null}<div style={{height:3,background:index===(spec.items||[]).length-1?accent:blue,marginTop:"auto"}}/></Panel>})}</div>;
const ConceptMap:React.FC<{spec:PrimaryEvidenceSpec;reveal:number}>=({spec,reveal})=><div style={{position:"absolute",left:105,right:105,top:250,bottom:spec.limitation?285:225,display:"flex",alignItems:"center",justifyContent:"space-between",gap:18}}>{(spec.steps||[]).map((step,index)=>{const local=interpolate(reveal,[index/Math.max(1,(spec.steps||[]).length),(index+1)/Math.max(1,(spec.steps||[]).length)],[0,1],clamp);return <React.Fragment key={step}><Panel style={{width:315,minHeight:180,opacity:local,transform:`scale(${.94+local*.06})`,padding:"26px 24px",display:"flex",alignItems:"center"}}><div><div style={{color:index===(spec.steps||[]).length-1?accent:blue,fontSize:18,fontWeight:900,letterSpacing:".12em"}}>{String(index+1).padStart(2,"0")}</div><div style={{color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:29,lineHeight:1.12,fontWeight:780,marginTop:14}}>{step}</div></div></Panel>{index<(spec.steps||[]).length-1?<div style={{color:blue,fontSize:34,opacity:local}}>→</div>:null}</React.Fragment>})}</div>;
const Boundary:React.FC<{spec:PrimaryEvidenceSpec;reveal:number}>=({spec,reveal})=><div style={{position:"absolute",left:90,right:90,top:245,bottom:spec.limitation?285:220,display:"grid",gridTemplateColumns:"1fr 1fr",gap:22}}>{[{title:spec.left||"",detail:spec.left_detail||"",color:blue},{title:spec.right||"",detail:spec.right_detail||"",color:accent}].map((item,index)=><Panel key={item.title} style={{padding:"35px 34px",opacity:interpolate(reveal,[index*.18,.58+index*.18],[0,1],clamp),display:"flex",alignItems:"center"}}><div><div style={{color:item.color,fontFamily:"Arial, Helvetica, sans-serif",fontSize:18,letterSpacing:".13em",fontWeight:900}}>{index?"DOES NOT ESTABLISH":"SUPPORTS"}</div><div style={{color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:34,lineHeight:1.08,fontWeight:830,marginTop:18}}>{item.title}</div><div style={{color:muted,fontFamily:"Arial, Helvetica, sans-serif",fontSize:25,lineHeight:1.28,fontWeight:560,marginTop:18}}>{item.detail}</div></div></Panel>)}</div>;
const Recap:React.FC<{spec:PrimaryEvidenceSpec;progress:number}>=({spec,progress})=><div style={{position:"absolute",left:85,right:85,top:210,bottom:205,display:"grid",gridTemplateColumns:"1fr 1fr 1.35fr",gap:18}}>{(spec.image_assets||[]).slice(0,3).map((asset,index)=><ImageFrame key={asset} src={asset} contain focus={{scale:1.02+index*.01,x:0,y:0}} progress={progress} style={{borderRadius:9}}/>)}</div>;
const Article:React.FC<{spec:PrimaryEvidenceSpec;reveal:number}>=({spec,reveal})=><div style={{position:"absolute",left:90,right:90,top:210,bottom:spec.limitation?280:215,display:"grid",gridTemplateColumns:"1.05fr 1.4fr",gap:24}}><Panel style={{padding:"36px 34px",display:"flex",alignItems:"center"}}><div><div style={{color:accent,fontSize:18,letterSpacing:".14em",fontWeight:900}}>OFFICIAL RESEARCH ARTICLE</div><div style={{color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:48,lineHeight:1.02,letterSpacing:"-.035em",fontWeight:860,marginTop:20}}>16</div><div style={{color:ink,fontFamily:"Arial, Helvetica, sans-serif",fontSize:30,lineHeight:1.12,fontWeight:760,marginTop:5}}>leading models stress-tested</div><div style={{color:muted,fontFamily:"Arial, Helvetica, sans-serif",fontSize:23,lineHeight:1.28,marginTop:20}}>Hypothetical corporate environments with email access and autonomous action.</div></div></Panel><div style={{display:"grid",gap:13}}>{(spec.items||[]).map((item,index)=>{const local=interpolate(reveal,[index*.16,.45+index*.16],[0,1],clamp);return <Panel key={item.label} style={{padding:"20px 24px",opacity:local,transform:`translateX(${(1-local)*22}px)`}}><div style={{display:"grid",gridTemplateColumns:"130px 1fr",gap:18,alignItems:"center"}}><div style={{color:blue,fontSize:18,letterSpacing:".12em",fontWeight:900}}>{item.label}</div><div><div style={{color:ink,fontSize:27,lineHeight:1.12,fontWeight:790}}>{item.value}</div>{item.detail?<div style={{color:muted,fontSize:21,lineHeight:1.2,marginTop:6}}>{item.detail}</div>:null}</div></div></Panel>})}</div></div>;

export const PrimaryEvidence:React.FC<{spec:PrimaryEvidenceSpec;durationInFrames:number}>=({spec,durationInFrames})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const reveal=spring({frame,fps,config:{damping:24,stiffness:95,mass:.9},durationInFrames:Math.min(40,durationInFrames)});const progress=interpolate(frame,[0,Math.max(1,durationInFrames-1)],[0,1],clamp);const fadeOut=interpolate(frame,[Math.max(1,durationInFrames-12),durationInFrames],[1,0],clamp);const opacity=reveal*fadeOut;let body:React.ReactNode;if(spec.kind==="split_documents")body=<SplitDocuments spec={spec} progress={progress}/>;else if(spec.kind==="official_document")body=<Document spec={spec} progress={progress}/>;else if(spec.kind==="official_figure")body=<Figure spec={spec} progress={progress}/>;else if(spec.kind==="official_screen")body=<Figure spec={spec} progress={progress} screen/>;else if(spec.kind==="image_sequence")body=<ImageSequence spec={spec} progress={progress}/>;else if(spec.kind==="source_timeline")body=<Timeline spec={spec} reveal={reveal}/>;else if(spec.kind==="source_article")body=<Article spec={spec} reveal={reveal}/>;else if(["boundary","comparison"].includes(spec.kind))body=<Boundary spec={spec} reveal={reveal}/>;else if(spec.kind==="recap")body=<Recap spec={spec} progress={progress}/>;else body=<ConceptMap spec={spec} reveal={reveal}/>;return <AbsoluteFill style={{opacity,background:`radial-gradient(circle at ${24+progress*12}% 18%,rgba(134,169,204,.16),transparent 34%),linear-gradient(145deg,#0B1420 0%,${ground} 58%,#050A11 100%)`,overflow:"hidden"}}><AbsoluteFill style={{opacity:.22,backgroundImage:"linear-gradient(rgba(134,169,204,.11) 1px,transparent 1px),linear-gradient(90deg,rgba(134,169,204,.11) 1px,transparent 1px)",backgroundSize:"72px 72px",transform:`translate(${progress*-10}px,${progress*-6}px)`}}/><Header spec={spec}/>{body}<Limitation text={spec.limitation}/><SourceBar spec={spec}/></AbsoluteFill>};
